version: 2.1

orbs:
  node: circleci/node@4.7.0  # Replace with the latest version

jobs:
  build:
    docker:
      - image: cimg/node:14.17  # Use the version that matches your project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
