version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:14.17  # Use the Node.js version that matches your project
    steps:
      - checkout
      - run: npm install
      - run: npm run build  # Replace with your project's build command

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
