version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd client
            npm install
            npm run build
      - save_cache:
          paths: [client/node_modules]
          key: frontend-build

  scan-frontend:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan Frontend
          command: |
            cd client
            npm audit fix --audit-level=critical

  hold-for-approval:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - run:
          name: "Awaiting Approval"
          command: echo "Deployment requires manual approval"

  deploy-frontend:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Deploying to AWS S3
          command: aws s3 sync ./client/build s3://appointmentsim/

  build-backend:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests
          command: |
            npm install
            npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  scan-backend:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Scan Backend
          command: |
            npm install
            npm audit fix --audit-level=critical

  deploy-backend:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "f4:e3:e0:4e:2d:e1:ce:b1:c0:e0:f5:40:3a:a4:8f:e2" 
      - run:
          name: Deploy to EC2
          command: |
            pwd
            ls -al
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-81-22-38.compute-1.amazonaws.com 'bash -s' < ./server/deploy_script.sh

  smoke-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Smoke Test Frontend
          command: |
            chmod +x ./client/smoke_test_frontend.sh
            ./client/smoke_test_frontend.sh
      - run:
          name: Smoke Test Backend
          command: |
            chmod +x ./server/smoke_test_backend.sh
            ./server/smoke_test_backend.sh

workflows:
  build_and_scan_and_deploy:
    jobs:
      - build-frontend
      - build-backend
      - scan-frontend:
          requires:
            - build-frontend
      - scan-backend:
          requires:
            - build-backend
      - hold-for-approval: 
          type: approval
          requires:
            - scan-frontend
            - scan-backend
      - deploy-frontend:
          requires:
            - hold-for-approval
      - deploy-backend:
          requires:
            - hold-for-approval
      - smoke-test:
          requires:
            - deploy-frontend
            - deploy-backend
