version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd client
            npm install
            npm run build
      - save_cache:
          paths: [client/node_modules]
          key: frontend-build

  scan-frontend:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan Frontend
          command: |
            cd client
            npm install
            npm audit fix --audit-level=critical

  # New Approval Job
  hold-for-approval:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - run:
          name: "Awaiting Approval"
          command: echo "Deployment requires manual approval"

  deploy-frontend:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Deploying to AWS S3
          command: aws s3 sync ./client/build s3://appointmentsim/

workflows:
  build_and_scan_and_deploy:
    jobs:
      - build-frontend
      - scan-frontend:
          requires:
            - build-frontend
      - hold-for-approval:  # Approval step before deployment
          type: approval
          requires:
            - scan-frontend
      - deploy-frontend:
          requires:
            - hold-for-approval
