version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:14.17  # Use the version that matches your project
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
