version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:14.17  # Use the version that matches your project
    steps:
      - checkout
      - run: npm install
      - run: npm run lint  # Code quality check step
      - run: npm test  # Run your test suite
      - run: npm run build  # Build your project

workflows:
  version: 2
  all_jobs:
    jobs:
      - build_and_test
