version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest # Specify the Docker image to use
    working_directory: ~/repo # Set the working directory
    steps:
      - checkout # Check out the code in the project's repository
      - run:
          name: Create frontend directory
          command: mkdir -p ~/repo/frontend # Create the frontend directory
      - run:
          name: Install dependencies
          command: |
            cd ~/repo/frontend
            npm install # Install npm dependencies, assuming a Node.js project
      # Add additional steps as needed for building/testing your frontend

workflows:
  version: 2
  buildfrontend:
    jobs:
      - build
